const router = require("express").Router();
const { requireAuth } = require("../middleware/auth");
const c = require("../controllers/userController");
router.get("/me",                          requireAuth, c.getMe);
router.put("/me",                          requireAuth, c.updateMe);
router.delete("/me",                       requireAuth, c.deleteAccount);
router.get("/me/watchlist",                requireAuth, c.getWatchlist);
router.post("/me/watchlist",               requireAuth, c.addToWatchlist);
router.delete("/me/watchlist/:contentId",  requireAuth, c.removeFromWatchlist);
router.get("/me/history",                  requireAuth, c.getHistory);
router.post("/me/history",                 requireAuth, c.saveProgress);
router.get("/me/notifications",            requireAuth, c.getNotifications);
router.put("/me/notifications/:id/read",   requireAuth, c.markNotifRead);
module.exports = router;
